### ISSUE TITLE
🎯 Tracking: Resolving nodes by `URI`

### ISSUE THREAD

**Issue by justlevine** [wp-graphql/wp-graphql#2366]
This is a tracker for all the issues with bad/missing results when resolving nodes by their URI.

The general problem stems from `NodeResolver`'s [attempt](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Data/NodeResolver.php#L75) to replicate [`WP::parse_request`](https://developer.wordpress.org/reference/classes/wp/parse_request/) with a provided `uri`. Assumingly, some of these are due to misordered conditionals, while others are missing edge cases.

## Proposed Work
As I see it, the ideal solve requires 3 steps:
- [x] Refactor `NodeResolver` to make the code less complex, and easier to test/iterate on. ( #2656 )
- [x] Add missing `wpunit` tests to `NodeByUriTest` to bring `NodeResolver::resolve_uri()` to 100%. ( #2659 )
- [x] Fix existing bugs in resolver ( #2680 )
- [ ] Research and add support for other edge cases, using the issues below as a baseline.

## Tracking:
- [x] #2066
- [x] #1850
- [x] #1687
- [x] #1639
- [x] #2190
- [x] #2178
- [x] #2394 
- [x] #1712 
- [x] #1910 
- [x] #1673
- [ ] #2514
- [ ] #2191

If I missed an issue or if you have a use case not referenced by an existing issue, **please share and I'll add it to the tracker**.

**Comment by jmotes-lapero** [comment]
@justlevine I just opened #2394 that could be added here I think.

**Comment by Ririshi** [comment]
A discussion thread I opened (#2714) falls under this category as well, as was pointed out by @justlevine.

**Comment by justlevine** [comment]
Update: most the issues tracked have been resolved as of v1.14.0.

- #2191 is blocked by #2491
- #2513 and #2514 need to be revalidated to see if the use of the new WP_Query handling in v1.14.0 resolved the issue tangentially.
- #2392 might be `invalid` as native WP behavior.

**Comment by justlevine** [comment]
Closing this out, as #2514 is only bug left on this list (as #2191 is more of an enhancement via #2491 at this point). Between that and the Issue Triage project sheet, this ticket is unnecessary for tracking progress/providing context.
