### ISSUE TITLE
Add core user meta to the User Type

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql#479]
Currently the core User type in the Schema doesn't include the user meta that is used by core, such as the fields here: https://github.com/WordPress/WordPress/blob/5c291d49de756db1dbfddfe3fd69709595800622/wp-includes/author-template.php#L116-L186

The User Type should include these core fields by default and support them in queries and `createUser` and `updateUser` mutations.

**Comment by TomerPacific** [comment]
@jasonbahl ,
I would like to take this issue on and get some pointers on where to begin.

**Comment by jasonbahl** [comment]
@tomerpacific I’m available tomorrow to chat on slack if that works. I believe I have a branch locally where I started some work on this. Will have to check.

**Comment by TomerPacific** [comment]
@jasonbahl ,
I am pretty certain there is a massive time difference between us, so a chat will not be desirable for me or you. Is there any way to explain it through mail?

**Comment by jasonbahl** [comment]
@jkhaui you're not wrong that documentation is lacking 😢 

I'm trying to get documentation updated for the new v0.1.0 version we released last week that adds new `register_graphql_*` functions that make it easier than ever to extend the GraphQL Schema. 

for your situation, you'd want to decide if one of the `Types` in the Schema already matches the shape of what you want to return for your `profilePic` field on users. 

For example, if the avatar is an image from the Media Library, you could use the existing type `MediaItem` as the Type to return. 

Then you could add a field to the users like so: 

```
add_action( 'register_graphql_types', function() {
  register_graphql_field( 'User', 'profilePic', [
    'type' => 'MediaItem', 
    'description' => __( 'Profile pic for the user', 'your-textdomain' ),
    'resolve' => function( $user ) {
        // Assuming the ID of the uploaded avatar is stored under the meta key `profile_pic`
        $profile_pic_id = get_user_meta( $user->ID, 'profile_pic', true );
        
        // Resolve the media item or return null
        return ! empty( $profile_pic_id ) ? DataSource::resolve_post_object( $profile_pic_id, 'attachment' ) : null;

    },
 ] );
} );
```

This would now allow you to query something like: 

```
{
   viewer {
       firstName
       lastName
       profilePic {
          id
          mediaItemId
          sourceUrl
       }
   }
}
```

**Comment by jkhaui** [comment]
Hey,

So I've successfully exposed some custom GraphQL fields for plugins that add post, term and comment meta to the WP database.

User meta is still proving tricky though. Imo it's because the custom user meta-keys I'm trying to expose have an array of fields for their meta-values (e g. Profilepic URL: "", profilepic description: "", etc.), rather than a single scalar type (e.g. String).

In this instance, should I be creating a custom object first? A bit unsure how to proceed.
Many thanks

**Comment by mashirozx** [comment]
> @jkhaui you're not wrong that documentation is lacking 😢
> 
> I'm trying to get documentation updated for the new v0.1.0 version we released last week that adds new `register_graphql_*` functions that make it easier than ever to extend the GraphQL Schema.
> 
> for your situation, you'd want to decide if one of the `Types` in the Schema already matches the shape of what you want to return for your `profilePic` field on users.
> 
> For example, if the avatar is an image from the Media Library, you could use the existing type `MediaItem` as the Type to return.
> 
> Then you could add a field to the users like so:
> 
> ```
> add_action( 'register_graphql_types', function() {
>   register_graphql_field( 'User', 'profilePic', [
>     'type' => 'MediaItem', 
>     'description' => __( 'Profile pic for the user', 'your-textdomain' ),
>     'resolve' => function( $user ) {
>         // Assuming the ID of the uploaded avatar is stored under the meta key `profile_pic`
>         $profile_pic_id = get_user_meta( $user->ID, 'profile_pic', true );
>         
>         // Resolve the media item or return null
>         return ! empty( $profile_pic_id ) ? DataSource::resolve_post_object( $profile_pic_id, 'attachment' ) : null;
> 
>     },
>  ] );
> } );
> ```
> 
> This would now allow you to query something like:
> 
> ```
> {
>    viewer {
>        firstName
>        lastName
>        profilePic {
>           id
>           mediaItemId
>           sourceUrl
>        }
>    }
> }
> ```

How can I pass a parameter `$comment` like `$user` in a `comments` field?

I mean, I hope to add a custom `mate` field in `comments`, just to get the data from the `$comment` object.

![image](https://user-images.githubusercontent.com/16148054/70337853-cf403f80-1886-11ea-8383-eb83ed70068b.png)

In normal WordPress development, we can use codes like below to get comment mate info:

```php
function customComment( $comment, $args, $depth ) {
    $GLOBALS['comment'] = $comment;
    echo get_avatar( $comment->comment_author_email, '80', '', get_comment_author() );
}

// In comments.php call the custom comment list
wp_list_comments( 'type=comment&callback=customComment' ); 
```

What is the `$user` like `$comment` object in WPGraphQL?

**Comment by jasonbahl** [comment]
@mashirozx ok, so you have registered a `mate` field to the `Comment` type. That means that the `first` argument passed to the resolver for that field will be the `$comment` object (an instance of the WPGraphQL Comment Model)

So, assuming you have already defined a `Mate` type, (it appears you have) you can do something like: 

```
register_graphql_field( 'Comment', 'mate', [
  'type' => 'Mate',
  'resolve' => function( \WPGraphQL\Model\Comment $comment, $args, $depth ) {
     $avatar = get_avatar( $comment->commentAuthorEmail, '80', '' );
  }
] );
```

**Comment by mashirozx** [comment]
> @mashirozx ok, so you have registered a `mate` field to the `Comment` type. That means that the `first` argument passed to the resolver for that field will be the `$comment` object (an instance of the WPGraphQL Comment Model)
> 
> So, assuming you have already defined a `Mate` type, (it appears you have) you can do something like:
> 
> ```
> register_graphql_field( 'Comment', 'mate', [
>   'type' => 'Mate',
>   'resolve' => function( \WPGraphQL\Model\Comment $comment, $args, $depth ) {
>      // The resolve function for the field gets passed down the Object of the Type it is resolving on. 
>      // Since this field is registered on the `Comment` Type, it will be passed down the Comment
>      // object (from the WPGraphQL Model Layer), and you can use that do
>      // resolve the field;
>     $mate = [
>         'avatar' => your_function_to_get_avatar(),
>         'level' => your_function_to_get_level(),
>         'vip' => your_function_to_get_vip_value(),
>      ];
>      return $mate;
>   }
> ] );
> ```

Thanks a lot 🧡🧡🧡

**Comment by bahiirwa** [comment]
Of the user meta above, these are currently working as early as 0.3.3
- [x] description
- [x] firstName
- [x] id
- [x] lastName
- [x] nickname
- [x] email
- [x] username

Which of these need implementation, I speak of the quote below:

> Currently the core User type in the Schema doesn't include the user meta that is used by core, such as the fields here: https://github.com/WordPress/WordPress/blob/5c291d49de756db1dbfddfe3fd69709595800622/wp-includes/author-template.php#L116-L186

is this all that is pending?

- [ ] admin_color
- [ ] comment_shortcuts
- [ ] display_name
- [ ] plugins_last_view
- [ ] plugins_per_page
- [ ] rich_editing
- [ ] syntax_highlighting
- [ ] activation_key
- [ ] level
- [ ] login
- [ ] nicename
- [ ] pass
- [ ] registered
- [ ] status
- [ ] url

These seem to be out date with WP 5.0 which is minimum supported for WPGraphQL
- [ ] aim
- [ ] yim
- [ ] jabber

**Comment by jasonbahl** [comment]
@bahiirwa yes, this looks correct. 

We could start with supporting them in queries, then follow up with supporting them in Mutations. 

I believe most of them are standard Scalars, with the exception of the `admin_color`. I believe that _might_ need its own Object Type to represent?

**Comment by jasonbahl** [comment]
@bahiirwa we should also consider more declarative naming. 


For example, this doesn't read well:
```
{
  user {
     commentShortcuts
   }
}
```

but this is more declarative of the intent of the field: 

```
{
  user {
     hasCommentShortcutsEnabled
  }
}
```

**Comment by bahiirwa** [comment]
Some of the pending fields earlier noted here actually exist but have a different way they are accessed in the GraphQL query. Such as 

display_name => returned as name
registered => returned as registeredDate
level => returned in capabilities as an array of levels to the capabilities.

These others do not come part and parcel of the WP_User class(I stand to be corrected). They are the pending set should #1279 be accepted as solution as is now.

- [ ] admin_color
- [ ] comment_shortcuts
- [ ] plugins_last_view
- [ ] plugins_per_page
- [ ] rich_editing
- [ ] syntax_highlighting

Should also make a PR to remove these 

- aim
- yim
- jabber

They are not in WP 5.0 - Minimum requirement of plugin or is there some other backward compat issue behind this implementation?

**Comment by therealgilles** [comment]
@jasonbahl I don't see much action on this topic. Is the recommendation to add the user fields we need with register_graphql_field() or ...?

**Comment by justlevine** [comment]
Removing `not stale` now that stalebot is behaving.

When we're ready to implement the list of missing fields is going to need to be reevaluated.

**Comment by josephfusco** [comment]
Relevant https://github.com/wp-graphql/wp-graphql/pull/2763

**Comment by jasonbahl** [comment]
Good news, this shipped. WPGraphQL v2.9.0 (Feb 2026) added `adminColor`, `hasRichEditingEnabled`, `hasSyntaxHighlightingEnabled`, and `hasCommentShortcutsEnabled` to the User type via #3571, joining `shouldShowAdminToolbar` from #2763, using the declarative naming we discussed in this thread. Mutation support for these preferences, and a more general way to map user options into the schema, is being explored in #3562, so follow along there if that part matters to you. Closing this as completed.
